In [1]:
import datetime as dt
import os
import pandas as pd

In [2]:
files = os.listdir("Temperature Data")
files.remove("DivisionofCalls.xlsx")
files

['trento, italy 2006-10-02 to 2006-11-11.csv',
 'trento, Italy 2006-11-12 to 2006-12-22.csv',
 'trento, italy 2006-12-23 to 2007-02-01.csv',
 'trento, Italy 2007-02-02 to 2007-03-14.csv',
 'trento, italy 2007-03-15 to 2007-04-24.csv',
 'trento, Italy 2007-04-25 to 2007-06-04.csv',
 'trento, italy 2007-06-05 to 2007-07-15.csv',
 'trento, italy 2007-07-16 to 2007-08-25.csv',
 'trento, italy 2007-08-26 to 2007-10-05.csv',
 'trento, italy 2007-10-06 to 2007-11-15.csv',
 'trento, italy 2007-11-16 to 2007-12-26.csv',
 'trento, italy 2007-12-27 to 2008-02-05.csv',
 'trento, italy 2008-02-06 to 2008-03-15.csv',
 'trento, italy 2008-03-16 to 2008-04-25.csv',
 'trento, italy 2008-04-26 to 2008-06-05.csv']

In [3]:
all_dfs = pd.DataFrame()
for file in files:
    new_df = pd.read_csv("Temperature Data/" + file)
    all_dfs = pd.concat([all_dfs, new_df], ignore_index=True)

In [4]:
all_dfs['datetime'] = all_dfs['datetime'].map(lambda x: dt.datetime.fromisoformat(x))
all_dfs.sort_values("datetime", inplace=True)

In [5]:
name_col = all_dfs['name']
all_dfs = all_dfs.select_dtypes(['number', 'datetime']).set_index('datetime').interpolate(method='time')
all_dfs.dropna(axis=1, how='all', inplace=True)
all_dfs.reset_index(inplace=True)
all_dfs['name'] = name_col

In [6]:
all_dfs

,datetime,temp,feelslike,dew,humidity,precip,precipprob,snow,snowdepth,windspeed,winddir,sealevelpressure,cloudcover,visibility,name
0,2006-10-02 00:00:00,9.0,6.4,8.8,98.92,0.000,0.0,0.0,0.0,17.3,221.0,1016.9,90.0,0.2,"trento, italy"
1,2006-10-02 01:00:00,9.0,6.8,8.8,98.80,0.000,0.0,0.0,0.0,14.1,208.0,1017.0,90.0,0.2,"trento, italy"
2,2006-10-02 02:00:00,9.1,6.9,8.9,98.59,0.000,0.0,0.0,0.0,15.0,190.0,1017.0,50.0,0.2,"trento, italy"
3,2006-10-02 03:00:00,8.9,6.1,8.8,99.15,0.000,0.0,0.0,0.0,19.3,203.0,1017.0,90.0,0.2,"trento, italy"
4,2006-10-02 04:00:00,8.8,6.4,8.7,99.64,0.000,0.0,0.0,0.0,15.5,223.0,1017.0,90.0,0.2,"trento, italy"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14707,2008-06-05 19:00:00,8.7,8.7,6.7,87.39,0.000,0.0,0.0,0.0,0.3,293.0,1010.9,90.0,1.7,"trento, italy"
14708,2008-06-05 20:00:00,8.1,8.1,7.2,93.88,0.182,100.0,0.0,0.0,0.4,307.0,1010.2,90.0,1.6,"trento, italy"
14709,2008-06-05 21:00:00,7.6,7.6,6.2,90.53,0.000,0.0,0.0,0.0,3.7,349.0,1009.9,90.0,1.7,"trento, italy"
14710,2008-06-05 22:00:00,7.1,6.3,6.2,93.96,0.000,0.0,0.0,0.0,5.4,351.0,1010.4,90.0,1.7,"trento, italy"
14711,2008-06-05 23:00:00,6.9,6.3,6.2,95.02,0.000,0.0,0.0,0.0,4.9,1.0,1010.8,92.6,1.6,"trento, italy"

In [7]:
all_dfs.to_csv("CSVFiles/CleanCSV/Deer/temperature_data.csv", index=False)